import { test } from "./skip-windows.mjs";
import assert from "node:assert/strict";
import {
  xmlEscape,
  deriveScheduleIds,
  renderPlist,
  renderWrapper,
  renderCronLine,
  filterCrontab,
} from "../scripts/bootstrap/render-schedule.mjs";

test("xmlEscape order: & first, then < > \" '", () => {
  assert.equal(xmlEscape(`a&b<c>d"e'f`), "a&amp;b&lt;c&gt;d&quot;e&apos;f");
});

test("renderPlist is byte-identical to the bootstrap heredoc (golden)", () => {
  const golden = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.llm-wiki-memory.42</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>MEMORY_DATA_DIR</key>
    <string>/d</string>
    <key>PATH</key>
    <string>/p1:/p2</string>
  </dict>
  <key>ProgramArguments</key>
  <array>
    <string>/n/node</string>
    <string>/s/cli.mjs</string>
    <string>cron-job</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Minute</key>
    <integer>0</integer>
  </dict>
</dict>
</plist>
`;
  assert.equal(
    renderPlist({
      label: "com.llm-wiki-memory.42",
      dataDir: "/d",
      nodeBin: "/n/node",
      cliPath: "/s/cli.mjs",
      cronPath: "/p1:/p2",
    }),
    golden,
  );
});

test("renderPlist escapes XML metacharacters in a path (& in the data dir)", () => {
  const out = renderPlist({
    label: "L",
    dataDir: "/a&b",
    nodeBin: "/n",
    cliPath: "/c",
    cronPath: "/p",
  });
  assert.match(out, /<string>\/a&amp;b<\/string>/);
  assert.doesNotMatch(out, /<string>\/bin\/sh<\/string>/, "no /bin/sh -c indirection");
  assert.match(out, /<string>cron-job<\/string>/);
});

test("renderWrapper is byte-identical to the bootstrap heredoc (golden)", () => {
  const golden = `#!/usr/bin/env bash
# Auto-generated by llm-wiki-memory bootstrap.sh — invoked HOURLY by cron.
# The cron-job subcommand handles compile + consolidate + structured
# attempt logging. Do NOT hand-edit; re-run bootstrap.sh to regenerate.
set -u
export MEMORY_DATA_DIR="/d"
export PATH="/p1:/p2"
exec "/n/node" "/s/cli.mjs" cron-job
`;
  assert.equal(
    renderWrapper({
      dataDir: "/d",
      cronPath: "/p1:/p2",
      nodeBin: "/n/node",
      cliPath: "/s/cli.mjs",
    }),
    golden,
  );
});

test("renderCronLine is the hourly (0 * * * *) line with the quoted wrapper + tag suffix", () => {
  assert.equal(
    renderCronLine({ wrapperPath: "/d/state/cron-daily.sh", tag: "# llm-wiki-memory:/a/proj" }),
    '0 * * * * "/d/state/cron-daily.sh" # llm-wiki-memory:/a/proj',
  );
});

test("deriveScheduleIds: label / plist / tag / wrapper (install ↔ uninstall lockstep on wsHash)", () => {
  const ids = deriveScheduleIds({
    wsHash: "999",
    workspaceDir: "/a/proj",
    dataDir: "/a/proj/.llm-wiki-memory",
    home: "/home/u",
  });
  assert.equal(ids.label, "com.llm-wiki-memory.999");
  assert.equal(ids.plistPath, "/home/u/Library/LaunchAgents/com.llm-wiki-memory.999.plist");
  assert.equal(ids.tag, "# llm-wiki-memory:/a/proj");
  assert.equal(ids.wrapperPath, "/a/proj/.llm-wiki-memory/state/cron-daily.sh");
});

test("filterCrontab drops only the EXACT-suffix line — a prefix sibling survives", () => {
  const tag = "# llm-wiki-memory:/a/proj";
  const input =
    [
      `0 * * * * "/a/proj/.llm/state/cron-daily.sh" ${tag}`,
      `0 * * * * "/a/proj2/.llm/state/cron-daily.sh" # llm-wiki-memory:/a/proj2`,
      "0 2 * * * /usr/bin/backup  # unrelated",
    ].join("\n") + "\n";
  const out = filterCrontab(input, tag);
  assert.ok(out.includes("/a/proj2"), "prefix-sibling workspace line KEPT");
  assert.ok(out.includes("/usr/bin/backup"), "unrelated cron line KEPT");
  assert.ok(!out.split("\n").some((l) => l.endsWith(tag)), "this workspace's exact line dropped");
});

test("filterCrontab drops ALL blank lines (interior too) and can append a line", () => {
  const out = filterCrontab("a\n\n\nb\n", "# none", '0 * * * * "/w" # t');
  assert.equal(out, 'a\nb\n0 * * * * "/w" # t\n');
});

test("filterCrontab of an all-ours/all-blank input yields empty", () => {
  assert.equal(filterCrontab('0 * * * * "/w" # t\n\n', "# t"), "");
});
