// Graph-shaped examples: message flow, boundaries, order and branching.
// flow, architecture, sequence, flowchart and state.
// Every spec draws from the same fictional subject: the llm-wiki-memory
// engine itself (capture hooks, distillation, compile, embeddings, recall,
// the MCP server, the git-backed wiki, and the hourly cron).

/** @type {{kind: string, name: string, caption: string, spec: any}[]} */
export const graphExamples = [
  {
    kind: "flow",
    name: "ingest-path",
    caption:
      "How a captured session becomes a durable leaf: hook, flush, distill, compile, and promotion into the wiki.",
    spec: {
      kind: "flow",
      id: "gx-ingest",
      title: "Capture-to-wiki ingest path",
      nodes: [
        { id: "hook", col: 0, row: 0, label: "SessionEnd hook" },
        {
          id: "flush",
          col: 0,
          row: 1,
          label: "flush worker",
          sub: "distill-by-chunks, map-reduce",
        },
        {
          id: "daily",
          col: 1,
          row: 0,
          label: "daily atom file",
          sub: "daily/2026-08-28.md",
          kind: "store",
        },
        { id: "compile", col: 1, row: 1, label: "compile step", kind: "focal" },
        { id: "cron", col: 1, row: 2, label: "hourly cron tick", sub: "cron-job.mjs" },
        { id: "knowledge", col: 2, row: 0, label: "knowledge leaf", kind: "store" },
        { id: "lessons", col: 2, row: 1, label: "self_improvement leaf", kind: "store" },
        { id: "wiki", col: 2, row: 2, label: "git-backed wiki", sub: "auto-commit" },
        {
          id: "embedCache",
          col: 2,
          row: 3,
          label: "embedding cache",
          sub: ".embeddings/embeddings.json",
          kind: "store",
        },
      ],
      edges: [
        { from: "hook", to: "flush", kind: "sync", label: "spawn worker (pid, session, turns)" },
        { from: "flush", to: "daily", kind: "store", label: "write N atom(s) to daily/*.md" },
        { from: "daily", to: "compile", kind: "focal", label: "promote candidate atoms" },
        { from: "cron", to: "compile", kind: "async", label: "hourly trigger: cli.mjs compile" },
        { from: "compile", to: "knowledge", kind: "store", label: "promote decision atom" },
        { from: "compile", to: "lessons", kind: "store", label: "promote lesson atom" },
        { from: "knowledge", to: "wiki", kind: "sync", label: "write leaf + auto-commit" },
        { from: "lessons", to: "wiki", kind: "sync", label: "write leaf + auto-commit" },
        { from: "wiki", to: "embedCache", kind: "async", label: "cli.mjs warm: embed cold leaves" },
        {
          from: "cron",
          to: "knowledge",
          kind: "async",
          label: "consolidate merges duplicate clusters",
          route: "over",
          global: true,
        },
      ],
      zones: [
        { label: "capture", nodes: ["hook", "flush"] },
        { label: "distillation", nodes: ["daily", "compile", "cron"] },
        { label: "durable store", nodes: ["knowledge", "lessons", "wiki", "embedCache"] },
      ],
    },
  },
  {
    kind: "architecture",
    name: "trust-boundary-map",
    caption:
      "The engine's processes, external calls, and disk storage grouped by trust boundary, from caller to git-backed wiki.",
    spec: {
      kind: "architecture",
      id: "gx-arch",
      title: "Engine surfaces by trust boundary",
      nodes: [
        { id: "session", col: 0, row: 0, label: "chat session" },
        { id: "hookProc", col: 0, row: 1, label: "PostToolUse hook" },
        { id: "router", col: 1, row: 0, label: "MCP tool router", kind: "focal" },
        { id: "recall", col: 1, row: 1, label: "recall engine" },
        { id: "compileEngine", col: 1, row: 2, label: "compile engine" },
        { id: "llm", col: 2, row: 0, label: "LLM provider", sub: "chat completion API" },
        { id: "embedder", col: 2, row: 1, label: "embedding backend", sub: "embeddinggemma-300m" },
        { id: "wiki", col: 3, row: 0, label: "git-backed wiki" },
        { id: "cache", col: 3, row: 1, label: "embedding cache" },
      ],
      edges: [
        { from: "session", to: "router", kind: "sync", label: "MCP stdio: recall_lessons" },
        {
          from: "hookProc",
          to: "compileEngine",
          kind: "async",
          label: "in-process import, no MCP hop",
        },
        { from: "router", to: "recall", kind: "sync", label: "chunked vector search" },
        {
          from: "router",
          to: "compileEngine",
          kind: "focal",
          label: "save_lesson (gated)",
          route: "right",
          lane: 40,
        },
        { from: "recall", to: "embedder", kind: "async", label: "embed query text" },
        {
          from: "recall",
          to: "cache",
          kind: "store",
          label: "read per-category vectors",
          route: "under",
        },
        { from: "compileEngine", to: "llm", kind: "async", label: "distill + judge calls" },
        {
          from: "compileEngine",
          to: "wiki",
          kind: "store",
          label: "write leaf + auto-commit",
          route: "over",
        },
        { from: "embedder", to: "cache", kind: "sync", label: "embedding vector" },
      ],
      zones: [
        { label: "agent process", nodes: ["session", "hookProc"] },
        { label: "MCP server", nodes: ["router", "recall", "compileEngine"] },
        { label: "external providers", nodes: ["llm", "embedder"] },
        { label: "local disk", nodes: ["wiki", "cache"] },
      ],
    },
  },
  {
    kind: "sequence",
    name: "gated-save-handshake",
    caption:
      "The gated save handshake: a duplicate probe runs first, so a near-duplicate becomes an update instead of a new leaf.",
    spec: {
      kind: "sequence",
      id: "gx-save",
      title: "Gated save with duplicate probe",
      actors: [
        { id: "session", label: "chat session" },
        { id: "router", label: "MCP tool router", kind: "focal" },
        { id: "dedup", label: "dedup probe", sub: "search_memory" },
        { id: "wiki", label: "git-backed wiki" },
      ],
      steps: [
        { phase: "gate check" },
        { from: "session", to: "router", label: "save_lesson(title, body, gate.userRequested)" },
        { from: "router", to: "router", label: "verify gate.userRequested === true" },
        { phase: "dedup probe" },
        { from: "router", to: "dedup", label: "near-duplicate query" },
        { from: "dedup", to: "router", label: "candidate leaf + similarity 0.92" },
        {
          note: "similarity above threshold: propose an update, not a new leaf",
          over: ["router", "dedup"],
        },
        { from: "router", to: "wiki", label: "write leaf + auto-commit", kind: "store" },
        { from: "router", to: "session", label: "saved: self_improvement/gate-audit.md" },
      ],
    },
  },
  {
    kind: "flowchart",
    name: "recall-ladder",
    caption:
      "The recall decision ladder: warm the cache if needed, search, and flag any hit that needs validation as a prior.",
    spec: {
      kind: "flowchart",
      id: "gx-recall",
      title: "Recall ladder",
      nodes: [
        {
          id: "start",
          col: 0,
          row: 0,
          label: "recall_lessons(query, filters)",
          shape: "terminator",
        },
        { id: "embedQuery", col: 0, row: 1, label: "embed query text" },
        { id: "d1", col: 0, row: 2, label: "cache warm for category?", shape: "diamond" },
        { id: "coldEmbed", col: 1, row: 2, label: "cold-embed up to maxColdPerRead" },
        { id: "search", col: 0, row: 3, label: "vector search top-k chunks" },
        { id: "d2", col: 0, row: 4, label: "any chunk above similarity floor?", shape: "diamond" },
        { id: "noHit", col: 1, row: 4, label: "return empty: no relevant memory" },
        {
          id: "d3",
          col: 0,
          row: 5,
          label: "leaf references code or system state?",
          shape: "diamond",
        },
        {
          id: "flagPrior",
          col: 1,
          row: 5,
          label: "flag as PRIOR: validate before relying",
          kind: "focal",
        },
        { id: "end", col: 0, row: 6, label: "return scored chunks", shape: "terminator" },
      ],
      edges: [
        { from: "start", to: "embedQuery" },
        { from: "embedQuery", to: "d1" },
        { from: "d1", to: "search", label: "yes" },
        { from: "d1", to: "coldEmbed", label: "no" },
        { from: "coldEmbed", to: "search" },
        { from: "search", to: "d2" },
        { from: "d2", to: "d3", label: "yes" },
        { from: "d2", to: "noHit", label: "no" },
        { from: "d3", to: "flagPrior", label: "yes" },
        { from: "d3", to: "end", label: "no" },
        { from: "flagPrior", to: "end" },
        { from: "noHit", to: "end" },
      ],
    },
  },
  {
    kind: "state",
    name: "leaf-lifecycle",
    caption:
      "A leaf's lifecycle from a captured daily atom through distillation, promotion, consolidation, and archival.",
    spec: {
      kind: "state",
      id: "gx-leaf",
      title: "Leaf lifecycle",
      nodes: [
        { id: "start", col: 0, row: 0, label: "", shape: "dot" },
        { id: "captured", col: 0, row: 1, label: "captured", sub: "daily/2026-08-28.md" },
        { id: "distilling", col: 0, row: 2, label: "distilling" },
        { id: "active", col: 0, row: 3, label: "active", kind: "focal" },
        { id: "consolidating", col: 1, row: 3, label: "consolidating" },
        { id: "archived", col: 0, row: 4, label: "archived", sub: "supersede-on-promote" },
        { id: "end", col: 0, row: 5, label: "", shape: "end" },
      ],
      edges: [
        { from: "start", to: "captured" },
        { from: "captured", to: "distilling", label: "flush worker" },
        { from: "distilling", to: "distilling", label: "retry [backoff]", kind: "async" },
        { from: "distilling", to: "active", label: "compile promotes atom" },
        { from: "active", to: "consolidating", label: "hourly cron tick" },
        { from: "consolidating", to: "archived", label: "merged into survivor" },
        { from: "active", to: "archived", label: "disable_document (manual)" },
      ],
    },
  },
];
